name: Example Workflow

on: [push]

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        SECRET: op://infra/Test1password/secret

    - name: Use Secret
      run: echo "Secret value is $SECRET"
